# Generated by Django 4.1.1 on 2022-09-22 01:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0005_profiles_delete_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profiles',
            new_name='UserProfile',
        ),
    ]
