# Generated by Django 4.1.1 on 2022-10-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='formuser',
            name='is_posts_admin',
            field=models.BooleanField(default=False),
        ),
    ]
