# Generated by Django 4.1.1 on 2022-09-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprofile', '0002_alter_post_post_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%d/%m/%Y/'),
        ),
    ]
