# Generated by Django 4.1.1 on 2022-09-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprofile', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images/%d/%m/%Y/'),
        ),
    ]
