# Generated by Django 4.1.1 on 2022-09-18 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webprofile', '0009_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_is_published',
            new_name='is_published',
        ),
    ]
