# Generated by Django 4.1.1 on 2022-09-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webprofile', '0011_quillpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuillPost',
        ),
    ]
