# Generated by Django 4.1.1 on 2022-09-24 21:05

from django.db import migrations, models
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webprofile', '0012_delete_quillpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostEditorJs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', django_editorjs.fields.EditorJsField()),
            ],
        ),
    ]
