# Generated by Django 4.1.1 on 2022-09-24 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webprofile', '0013_posteditorjs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posteditorjs',
            old_name='content',
            new_name='body',
        ),
    ]
