# Generated by Django 4.1.1 on 2022-09-24 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webprofile', '0015_posts_delete_posteditorjs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
