# Generated by Django 4.1.1 on 2022-09-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprofile', '0018_delete_posts_post_url_title_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
