# Generated by Django 4.1.1 on 2022-10-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprofile', '0019_alter_post_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='url_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
