# Generated by Django 4.1.1 on 2022-10-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprofile', '0020_alter_post_category_alter_post_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(max_length=200),
        ),
    ]
