# Generated by Django 4.1.1 on 2022-10-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprofile', '0021_alter_post_category_alter_post_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_for_main_page',
            field=models.BooleanField(default=False),
        ),
    ]
