# Generated by Django 4.1.1 on 2022-10-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprofile', '0022_post_is_for_main_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_locked_for_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='review_reason',
            field=models.TextField(default='Sinalizado como conteúdo potencialmente sensível'),
        ),
    ]
