# Generated by Django 4.1.1 on 2022-10-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprofile', '0028_alter_post_review_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
